RESOURCES_PATH = "Resources/"
PATH_TO_VIDEO = RESOURCES_PATH + "video5.mp4"
PATH_TO_MODEL = RESOURCES_PATH + "haarcascade_frontalface_default.xml"
SOURCE = "VIDEO"
JSON_PATH_PRE = "/jsonFiles/PreProcessResults.json"
PATH_TO_JSON_PRE = RESOURCES_PATH + JSON_PATH_PRE
VIDEO_PREVIEW_POS = True
VIDEO_PREVIEW_PRE = True
